.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. burritocoin_qt test_burritocoin_qt
clean: FORCE
	$(MAKE) -C .. burritocoin_qt_clean test_burritocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_burritocoin_qt_check
burritocoin-qt burritocoin-qt.exe: FORCE
	 $(MAKE) -C .. burritocoin_qt
