#ifndef BURRITOCOIN_CHAINPARAMSSEEDS_H
#define BURRITOCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the burritocoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    // 129.146.160.229:9227  (BurritoCoin mainnet seed node)
    // BIP155: 0x01=IPv4, 0x04=4-byte addr, then addr bytes, then port big-endian
    0x01, 0x04, 0x81, 0x92, 0xA0, 0xE5, 0x24, 0x0B,
};

static const uint8_t chainparams_seed_test[] = {
    // 129.146.160.229:19227  (no testnet is currently run; see
    // contrib/seeds/nodes_test.txt)
    // BIP155: 0x01=IPv4, 0x04=4-byte addr, then addr bytes, then port big-endian
    0x01, 0x04, 0x81, 0x92, 0xA0, 0xE5, 0x4B, 0x1B,
};
#endif // BURRITOCOIN_CHAINPARAMSSEEDS_H
