#ifndef BURRITOCOIN_CHAINPARAMSSEEDS_H
#define BURRITOCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the burritocoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 *
 * BRTO-TODO: populate once BurritoCoin network nodes are live.
 * The previous entries were seed nodes from the upstream fork and have been removed.
 */
static const uint8_t chainparams_seed_main[] = {
    // No fixed seeds yet — BurritoCoin mainnet has not launched.
};

static const uint8_t chainparams_seed_test[] = {
    // No fixed seeds yet — BurritoCoin testnet has not launched.
};
#endif // BURRITOCOIN_CHAINPARAMSSEEDS_H
