description "BurritoCoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env BURRITOCOIND_BIN="/usr/bin/burritocoind"
env BURRITOCOIND_USER="burritocoin"
env BURRITOCOIND_GROUP="burritocoin"
env BURRITOCOIND_PIDDIR="/var/run/burritocoind"
# upstart can't handle variables constructed with other variables
env BURRITOCOIND_PIDFILE="/var/run/burritocoind/burritocoind.pid"
env BURRITOCOIND_CONFIGFILE="/etc/burritocoin/burritocoin.conf"
env BURRITOCOIND_DATADIR="/var/lib/burritocoind"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # burritocoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$BURRITOCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run burritocoind."
        echo "The setting must appear in $BURRITOCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"BurritoCoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$BURRITOCOIND_PIDDIR"
    chmod 0755 "$BURRITOCOIND_PIDDIR"
    chown $BURRITOCOIND_USER:$BURRITOCOIND_GROUP "$BURRITOCOIND_PIDDIR"
    chown $BURRITOCOIND_USER:$BURRITOCOIND_GROUP "$BURRITOCOIND_CONFIGFILE"
    chmod 0660 "$BURRITOCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$BURRITOCOIND_PIDFILE" \
    --chuid $BURRITOCOIND_USER:$BURRITOCOIND_GROUP \
    --exec "$BURRITOCOIND_BIN" \
    -- \
    -pid="$BURRITOCOIND_PIDFILE" \
    -conf="$BURRITOCOIND_CONFIGFILE" \
    -datadir="$BURRITOCOIND_DATADIR" \
    -disablewallet \
    -daemon

